{{- if .Values.agentCollector.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agent
  labels:
    {{- include "ollyscale-otel.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agent
subjects:
  - kind: ServiceAccount
    name: agent
    namespace: {{ .Release.Namespace }}
{{- end }}
